### PR TITLE
Secure hive metastore password

### PR DESCRIPTION
**Pull request by DrRayWang**
secure hive metastore password with credential provider, remove it from hive-site.xml and related changes

### CODE REVIEW

**Comment by DrRayWang** [comment]
this pull request is covered by PR#266, so can be merged in PR#266.

**Comment by DrRayWang** [comment]
handled in PR#266

**Comment by cbaenziger** [comment]
Leaving this open as #266 does not cover concealing the Hive metastore password using Hadoop credentials. This is needed to actually secure the Hive password.

**Comment by vt0r** [comment]
Closing for cleanup. Feel free to reopen if this work gets picked up later on.

**Pull request closed without merging**
