### PR TITLE
Add a test for parse_cluster_txt

### PR DESCRIPTION
**Pull request by cbaenziger**
This adds a unit test for the `cluster_data` library. More to come but want to get a small PR outstanding...

### CODE REVIEW

**Comment by http-418** [comment]
Why does this change C-A-R?

**Comment by cbaenziger** [comment]
Because of CAR's use of [cluster_data](https://github.com/cbaenziger/chef-bach/blob/0c4c92e53351f29d7c4ac0c3e66b9bf4d28deb49/cluster_assign_roles.rb#L27)

**Comment by cbaenziger** [comment]
Fun rebaising this just pull all of my changes out without a conflict somehow. Finding out what's up...

**Comment by cbaenziger** [comment]
Okay now this is happy

**Comment by http-418** [comment]
I still don't understand why C-A-R needed to change.  What is the point of having a method called "parse_cluster_txt" take an argument that is always the same?  Shouldn't that be a default value?

**Comment by cbaenziger** [comment]
@http-418 How can you test this function without being able to handle an input? Also for the sake of being able to handle a cluster.txt for a Hadoop or Kafka cluster, this aides in being able to select a desired cluster type by walking the various cluster.txt's we have in the stub-environments directory.

**Comment by cbaenziger** [comment]
As to why `cluster_assign_roles.rb` changes, can you explain what the challenge is? The function's prototype changed and C-A-R is a consumer which was updated, there is no other change to C-A-R?

**Comment by http-418** [comment]
OK.  Add a default argument -- the signature can be unchanged as far as C-A-R is concerned, and your new test has an easy way to inject alternate values.

**Comment by aespinosa** [comment]
already included in #788

**Pull request closed without merging**
