### PR TITLE
Spark 2.0.2 with hadoop 2.7 support

### PR DESCRIPTION
**Pull request by pu239ppy**
Deploy Spark 2.0.2 package built with hadoop 2.7 support

**Breaking**: Due to the package layout changes we will no longer be able to deploy Spark 1.x

### CODE REVIEW

**Comment by ekund** [comment]
Waiting patiently for this feature, thanks for working on it!

**Comment by pu239ppy** [comment]
Built from scratch and tested

**Comment by pu239ppy** [comment]
Added environment variables to help SPARK find HADOOP_HOME and HADOOP_CONF
In addition LD_LIBRARY_PATH to support short-circuit hdfs

**Comment by vt0r** [comment]
I created a merge conflict by merging your `/home/$(whoami)` --> `${HOME}` fix, so if you can rebase on current master, we can merge this.

**Comment by pu239ppy** [comment]
Rebased

**Pull request merged**
