### PR TITLE
chef vault mysql hive password

### PR DESCRIPTION
**Pull request by DrRayWang**
Chef vault mysql-hive-password with related changes

### CODE REVIEW

**Comment by amithkanand** [comment]
This PR doesn't work. Recipe `hive.rb` is not listed in the run_list of any role. Also, code for removing `hive` password should move to `hive_hcatalog` recipe.

**Comment by http-418** [comment]
Ray, this will need to be manually rebased before merge.

In addition, I'd really like to see the calls into chef-vault moved out of compile time.  It can be very frustrating to troubleshoot an issue that occurs before chef-shell is usable.  I see nothing in this changeset that cannot be migrated into lazy helpers and/or lambdas.

**Comment by DrRayWang** [comment]
This PR also breaks for sitting long here. The problem I see is the find_resource.sh running in BCPC-Hadoop-Worker part does not work anymore. The runlist I see when find_resource.sh running is not right. It only includes some basic roles and recipes, such as networking. The full runlist for Worker role is loaded for some reason. Will try to figure out why.

**Comment by http-418** [comment]
I'm going to give this another shot this afternoon.

**Comment by vt0r** [comment]
Closing for cleanup. Feel free to reopen if this work gets picked up later on.

**Pull request closed without merging**
