### PR TITLE
Avoid openjdk installation and use Oracle Java

### PR DESCRIPTION
**Pull request by amithkanand**
Since we have started using Oracle Java, this PR removes installation of OpenJDK.

### CODE REVIEW

**Comment by bijugs** [comment]
Any reason we want to avoid OpenJDK. It will be better to have an option to choose between JDK flavors so that users can choose. One compelling reason for OpenJDK support is the feature additions and frequent bug fixes along with the compelling reason of being OpenSource.

**Comment by amithkanand** [comment]
We are removing it from our script. The upstream cookbook that we use does have an option to install OpenJDK and we need to set attributes accordingly. I don't see any need to have two JDK's installed simultaneously on the machine.

**Comment by pu239ppy** [comment]
As long as we have an option to easily switch between the two if a need arises.

**Comment by cbaenziger** [comment]
Sorry to rain on the parade, but did any one see if setting `node[:bcpc][:binary_server_url]` will still work for this? I'm a bit concerned about races calling `get_binary_server_url` in an attribute file.

**Pull request merged**
