### PR TITLE
Secure oozie passwords

### PR DESCRIPTION
**Pull request by DrRayWang**
chef vault oozie keystore password and related changes

### CODE REVIEW

**Comment by cbaenziger** [comment]
Please secure the permissions from casual viewing or use HADOOP credentials password storage in `oozie-site.xml` for its MySQL password.

**Comment by http-418** [comment]
Ray, I would really like to see the vault activities moved out of the Chef 'compile' phase.  

Please move calls to get_config into lazy helpers and/or lambdas.

**Comment by http-418** [comment]
This fails to converge.

```
                             
    - change group from '' to 'oozie'                                                                                  

  * ruby_block[oozie-database-creation] action runWarning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
  setting OOZIE_CONFIG=/etc/oozie/conf
  setting OOZIE_DATA=/var/lib/oozie
  setting OOZIE_LOG=/var/log/oozie
  setting OOZIE_LOG_DIR=/var/log/oozie
  setting OOZIE_PID_DIR=/var/run/oozie
  setting OOZIE_CATALINA_HOME=/usr/lib/bigtop-tomcat
  setting CATALINA_TMPDIR=/tmp
  setting CATALINA_PID=/var/run/oozie/oozie.pid
  setting CATALINA_BASE=/usr/hdp/current/oozie-client/oozie-server
  setting CATALINA_OPTS="-Xmx512m -XX:MaxPermSize=64m"
  setting OOZIE_HTTPS_PORT=11443
  setting OOZIE_HTTPS_KEYSTORE_PASS=R9GaZMoYbrWYn4OPDTIR
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.port=${OOZIE_HTTPS_PORT}"
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.keystore.pass=${OOZIE_HTTPS_KEYSTORE_PASS}"
  setting JAVA_HOME=/usr/lib/jvm/java-7-oracle-amd64
  setting JAVA_LIBRARY_PATH=/usr/lib/hadoop/lib/native/Linux-amd64-64
  setting OOZIE_CONFIG=/etc/oozie/conf
  setting OOZIE_DATA=/var/lib/oozie
  setting OOZIE_LOG=/var/log/oozie
  setting OOZIE_LOG_DIR=/var/log/oozie
  setting OOZIE_PID_DIR=/var/run/oozie
  setting OOZIE_CATALINA_HOME=/usr/lib/bigtop-tomcat
  setting CATALINA_TMPDIR=/tmp
  setting CATALINA_PID=/var/run/oozie/oozie.pid
  setting CATALINA_BASE=/usr/hdp/current/oozie-client/oozie-server
  setting CATALINA_OPTS="-Xmx512m -XX:MaxPermSize=64m"
  setting OOZIE_HTTPS_PORT=11443
  setting OOZIE_HTTPS_KEYSTORE_PASS=R9GaZMoYbrWYn4OPDTIR
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.port=${OOZIE_HTTPS_PORT}"
  setting CATALINA_OPTS="$CATALINA_OPTS -Doozie.https.keystore.pass=${OOZIE_HTTPS_KEYSTORE_PASS}"
  setting JAVA_HOME=/usr/lib/jvm/java-7-oracle-amd64
  setting JAVA_LIBRARY_PATH=/usr/lib/hadoop/lib/native/Linux-amd64-64

Validate DB Connection

Error: Could not connect to the database: org.apache.oozie.service.ServiceException: E0024: Oozie configuration directory does not exist [/etc/oozie/conf/oozie-site.xml]

Stack trace for the error was (for debug purposes):
--------------------------------------
java.lang.Exception: Could not connect to the database: org.apache.oozie.service.ServiceException: E0024: Oozie configuration directory does not exist [/etc/oozie/conf/oozie-site.xml]
        at org.apache.oozie.tools.OozieDBCLI.validateConnection(OozieDBCLI.java:894)
        at org.apache.oozie.tools.OozieDBCLI.createDB(OozieDBCLI.java:188)
        at org.apache.oozie.tools.OozieDBCLI.run(OozieDBCLI.java:127)
        at org.apache.oozie.tools.OozieDBCLI.main(OozieDBCLI.java:78)
Caused by: org.apache.oozie.service.ServiceException: E0024: Oozie configuration directory does not exist [/etc/oozie/conf/oozie-site.xml]
        at org.apache.oozie.service.ConfigurationService.loadConf(ConfigurationService.java:218)
        at org.apache.oozie.service.ConfigurationService.init(ConfigurationService.java:140)
        at org.apache.oozie.service.Services.setServiceInternal(Services.java:383)
        at org.apache.oozie.service.Services.<init>(Services.java:111)
        at org.apache.oozie.tools.OozieDBCLI.getJdbcConf(OozieDBCLI.java:165)
        at org.apache.oozie.tools.OozieDBCLI.createConnection(OozieDBCLI.java:882)
        at org.apache.oozie.tools.OozieDBCLI.validateConnection(OozieDBCLI.java:890)
        ... 3 more
Caused by: java.io.FileNotFoundException: /etc/oozie/conf/oozie-site.xml (Permission denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at org.apache.oozie.service.ConfigurationService.loadConf(ConfigurationService.java:211)
        ... 9 more
--------------------------------------


    - execute the ruby block oozie-database-creation                                                                   

  * service[generally run oozie] action enable
    - enable service service[generally run oozie]                                                                      

  * service[generally run oozie] action start
    - start service service[generally run oozie]                                                                       

  * ruby_block[Oozie Down] action run[2015-11-25T12:43:47-05:00] FATAL: Oozie is reported as down for more than 5 seconds -- Connection exception has occurred [ java.net.ConnectException Connection refused ]. Trying after 1 sec. Retry count = 1
Connection exception has occurred [ java.net.ConnectException Connection refused ]. Trying after 2 sec. Retry count = 2
Connection exception has occurred [ java.net.ConnectException Connection refused ]. Trying after 4 sec. Retry count = 3
Connection exception has occurred [ java.net.ConnectException Connection refused ]. Trying after 8 sec. Retry count = 4
Error: IO_ERROR : java.io.IOException: Error while connecting Oozie server. No of retries = 4. Exception = Connection refused

```

**Comment by DrRayWang** [comment]
Seem my coding's sitting there for three months, many things changed to make it not working anymore. I will check it.

**Comment by DrRayWang** [comment]
Before this pull request get merged, another pull request PR#266 needs to be merged before this. It is https://github.com/bloomberg/chef-bach/pull/266

**Comment by vt0r** [comment]
Closing for cleanup. Feel free to reopen if this work gets picked up later on.

**Pull request closed without merging**
