### PR TITLE
Rename cookbook bcpc-hadoop to bach_hadoop

### PR DESCRIPTION
**Pull request by amithkanand**
This PR renames `bcpc-hadoop` to `bach_hadoop`.

### CODE REVIEW

**Comment by amithkanand** [comment]
I have cluster that I build after renaming the cookbook.

**Comment by ekund** [comment]
LGTM

**Comment by pu239ppy** [comment]
We have a few external cookbooks that depends on this name.

**Comment by amithkanand** [comment]
We will have to fix those external cookbooks as well. None of the upstream cookbook that we use depends on `bcpc-hadoop`.

**Comment by amithkanand** [comment]
Closing this PR as this is too old with many merge conflicts.

**Pull request closed without merging**
