### PR TITLE
Enable HDFS Audit logging

### PR DESCRIPTION
**Pull request by kiiranh**
This PR fixes Issue #308 .

### CODE REVIEW

**Comment by cbaenziger** [comment]
I would rather see you modify the [`hdp_log4j.properties.erb`](https://github.com/bloomberg/chef-bach/blob/78316e384c4093ddab81c60d9bac06c990368387/cookbooks/bcpc-hadoop/templates/default/hdp_log4j.properties.erb#L101) file instead of `hdp_hadoop-env.sh.erb`.

**Comment by kiiranh** [comment]
It seems the hdfs-audit logs all hdfs operations (INFO log level), which would be too verbose on an active cluster. I'm trying to find out if these are going to be useful in tracing major issues like HDFS failure of JN/NN formatting.

**Comment by kiiranh** [comment]
Doing it in [hdp_log4j.properties.erb](https://github.com/bloomberg/chef-bach/blob/78316e384c4093ddab81c60d9bac06c990368387/cookbooks/bcpc-hadoop/templates/default/hdp_log4j.properties.erb#L101) means the setting will be used by all hadoop components e.g.: yarn since the template is used in [hadoop_config.rb](https://github.com/bloomberg/chef-bach/blob/a12a1f2c6b9a4bacdd718d26a7e730ad53369c08/cookbooks/bcpc-hadoop/recipes/hadoop_config.rb#L16-L36) included by the recipes for other hadoop components too. At this point we want this enabled only for HDFS.

**Comment by cbaenziger** [comment]
Per recommendations from Hortonworks, we should also set the following in `hdfs-site.xml`:
```
<property>
  <name>dfs.namenode.audit.log.async</name>
  <value>true</value>
</property>
````

**Comment by kiiranh** [comment]
@cbaenziger Made suggested changes. Please note that the `hdfs-audit.log` created after this change will still not track `hdfs dfsadmin` functions, but just the following HDFS functions:
* create
* delete
* getfileinfo
* listStatus
* mkdirs
* open
* rename
* setPermission
* setTimes

So if someone were to execute a `hdfs dfsadmin` function we would know what changed on hdfs (depending on whether the dfsadmin function changes anything), but not who initiated it.

**Comment by http-418** [comment]
This converges and works for me.

**Comment by kiiranh** [comment]
Do we set the Logging level to `WARNING` by default? or leave it as `INFO`?

**Pull request merged**
