### PR TITLE
Remove hardcoded cookbook versions

### PR DESCRIPTION
**Pull request by cbaenziger**
- This reverts the change from chef-bcpc [issue 266](https://github.com/bloomberg/chef-bcpc/issues/266) which seems to be resolved in the current apt cookbook.
- This reverts the change from our initial Chef 11 [commit](https://github.com/bloomberg/chef-bach/commit/d6e431e0c18e7d2897028bb59cd3c736397ca580#diff-95d29768b114a017d5a3307f0e57eb09) which hard coded chef-client to version 3.0.6
- This also updates the list of cookbooks in `setup_chef_cookbooks.sh` to have each cookbook on its own line to aide in `git blame` being useful for seeing when things changed per cookbook

### CODE REVIEW

**Comment by kiiranh** [comment]
Are we going to keep this code after PR #104 ?

**Comment by cbaenziger** [comment]
No; this code should go away for #104

**Comment by cbaenziger** [comment]
I'm impatient can we merge this while we wait for PR #104 ?

**Comment by kiiranh** [comment]
This will have to be rebased to be merged.

**Pull request closed without merging**
