### PR TITLE
Provide GitHub workflow for README Contributing section

### PR DESCRIPTION
**Pull request by cbaenziger**
This adds a pointer to our current GitHub workflow (with color matched labels) as stored in our `pages` branch.

### CODE REVIEW

**Comment by cbaenziger** [comment]
Let me drop in the deployment types we support while I'm dorking in the README. Just a few minutes for that...

**Comment by ekund** [comment]
Can you squash the commits?

**Comment by cbaenziger** [comment]
Ah I thought the commits were pretty reasonable? What'd you want to group all three under?

**Comment by ekund** [comment]
I'd group them under "Improved Documentation of SDLC".  I thought in general we try to keep 1 commit per PR.

**Comment by cbaenziger** [comment]
Will squash under that banner. (One commit per feature is the desire. That way we can tell what went in where most easily. No need for a work log, but don't want to hide things in commits either.)

**Pull request merged**
