### PR TITLE
Fix the zookeeper environment jvm flags.

### PR DESCRIPTION
**Pull request by ronny-macmaster**
The previous method of assignment does not work in bash.
The alternative to the new approach is to use backslashes within one multi-line string.

### CODE REVIEW

**Comment by ronny-macmaster** [comment]
This is not a crucial bugfix, and merging #1302 would render this irrelevant.

**Comment by cbaenziger** [comment]
For reference, this is still a relevant fix in master @ronny-macmaster.

**Comment by cbaenziger** [comment]
This looks good to me too

**Comment by vt0r** [comment]
Is this PR still necessary after #1302 ?

**Comment by ronny-macmaster** [comment]
Yes, apparently #1302 doesn't revert any changes to [zk-zookeeper-env.sh.erb](cookbooks/bcpc-hadoop/templates/default/zk_zookeeper-env.sh.erb). We still need this change for this env script to actually work.

**Comment by ronny-macmaster** [comment]
This will break zookeeper if libjvmkill.so doesn't exist on the cluster.

**Pull request merged**
