### PR TITLE
Remove unused inherited bcpc-centos cookbook

### PR DESCRIPTION
**Pull request by kiiranh**
This PR removes unused code inherited from bcpc. Some changes are as simple as deleting cookbooks entirely and some changes will require carefully modifying references to deleted code in the used code(e.g.: library code in `bcpc` uses `Role[BCPC-Headnode]` but that role is not used in chef-bach).

This fixes issue #102

### CODE REVIEW

**Comment by kiiranh** [comment]
This is still WIP. Will add a comment when all changes are made and this is ready for review.

**Comment by kiiranh** [comment]
After discussion with Clay, this PR should only delete cookbook `bcpc-centos` which has been done. Rest of the code changes are more elaborate and would take much time and effort.

**Comment by kiiranh** [comment]
This has been tested on mac vm cluster. All services verified working using the usual sanity checks. Ready for review/merge.

**Comment by bijugs** [comment]
@kiiranh LGTM. Just for completeness may want to kick-off an openstack cluster. Thoughts?

**Comment by cbaenziger** [comment]
This looks good but would you mind also pulling [cobbler-centos.rb](https://github.com/bloomberg/chef-bach/blob/725bef69b3ccc13fd592c202b8d4ff009719cc27/cookbooks/bcpc/recipes/cobbler-centos.rb) and [the CentOS image downloads](https://github.com/bloomberg/chef-bach/blob/97d86fa9870d77b3f2cb4ea146178043729982a1/build_bins.sh#L132-L141) with this?

**Comment by kiiranh** [comment]
Cleaned up mote cents code/references. Tested on vbox vm cluster. Please review/merge.
@bijugs These changes do not affect and working functionality. Even so, if you feel comfortable I'll test this on openstack.

**Comment by bijugs** [comment]
@kiiranh as discussed we don't need to test this on openstack.

**Comment by kiiranh** [comment]
@bijugs Thanks! Would you mind merging it?

**Pull request merged**
