### PR TITLE
Pickup more stuff from PR#817

### PR DESCRIPTION
**Pull request by aespinosa**
Since we actually use a symbol in line 37.

### CODE REVIEW

**Comment by vt0r** [comment]
Will need to verify the following two commits get cherry-picked here:

https://github.com/bloomberg/chef-bach/pull/817/commits/de144eb077a17bba9fd2166b8b86331fa2bff926

https://github.com/bloomberg/chef-bach/pull/817/commits/51cfd88a55b7eafa53940350f8a177d5b28fa3e7

**Comment by aespinosa** [comment]
@vt0r Here's the final diff between the original PR and this branch https://gist.github.com/aespinosa/471f2f638921918a003adc3c8da21527

Looks good to me now

**Comment by aespinosa** [comment]
Other PRs that got clobbered:
* #837 (Spnego)

**Comment by aespinosa** [comment]
@vt0r confirmed that the two PRs are in head even though the chef12 PR shows they were clobbered.  This PR should be good to go

**Pull request merged**
