### PR TITLE
Set spark.dynamicAllocation.maxExecutors

### PR DESCRIPTION
**Pull request by jmh045000**
Set the max executors to 2.

### CODE REVIEW

**Comment by vt0r** [comment]
@jmh045000 - Would you mind clarifying what issue you're experiencing and how setting a static max of 2 executors resolves it, please? Is the default `infinity` utilizing too many resources somewhere? If so, perhaps we would rather base the max number on something we can pull from Ohai instead?

**Comment by jmh045000** [comment]
`infinity` leaves the problem of malformed spark tasks taking all the resources within a cluster or shared queue.  For instance, reading a large, fragmented hive table can spawn >40k tasks.  With `infinity` `maxExecutors` we can end up spawning several hundred executors almost instantaneously.

Note, this can still be overridden by providing `--conf spark.dynamicAllocation.maxExecutors=0` on the command line (or some appropriate alternative).

The other resolution, that I'm not sure about, is preventing a single queue from taking an entire cluster to start with (maybe YARN's scheduler can do this, I'm not sure).

**Comment by pu239ppy** [comment]
@jmh045000 You can definitely do this with schedulers

**Comment by cbaenziger** [comment]
@jmh045000 I'm happy to merge this giving us the overrideable attribute then we can set that in a wrapper cookbook for our various physical clusters if you want to make the change?

**Comment by vt0r** [comment]
We have made several scheduler improvements since this issue was created, and we've also _educated_ tenants who previously had abusive jobs. Things have been much better since, so I think we can safely close this.

**Comment by cbaenziger** [comment]
This is better than not accepting it; merging.

**Pull request merged**
