### PR TITLE
Add Phoenix properties to enable Phoenix namespace mapping

### PR DESCRIPTION
**Pull request by bijugs**
The attributes were set with ``Phoenix`` defaults.

### CODE REVIEW

**Comment by cbaenziger** [comment]
Thanks Biju; shall I hold off to setup release notes on how to migrate the system tables and for the user namespaces to be enabled as well?

**Comment by ronny-macmaster** [comment]
This change when deployed to cluster, requires handholding with Phoenix users/tenants. This will impact Phoenix users.

**Comment by ronny-macmaster** [comment]
Need to test with HDP 2.6.3 @bijugs

**Comment by bijugs** [comment]
@ronny-macmaster. @RiteshVajariya  Certainly we can test once ``chef-bach`` is moved to ``HDP 2.6.3``.

**Comment by saumilmayani** [comment]
To Enable Namespace mapping, property values should be corrected.
```
cookbooks/bcpc-hadoop/attributes/hbase.rb
+  site_xml['phoenix.schema.isNamespaceMappingEnabled'] = true
+  site_xml['phoenix.schema.mapSystemTablesToNamespace'] = true
```

with HDP 2.6.3, we have acls for phoenix in place.
PHOENIX-4198 Remove need for users to have write permission to SYSTEM.CATALOG table.

To Implement security,
```
cookbooks/bcpc-hadoop/attributes/hbase.rb
+  site_xml['phoenix.schema.isNamespaceMappingEnabled'] = true
+  site_xml['phoenix.schema.mapSystemTablesToNamespace'] = true
+  site_xml['phoenix.acls.enabled'] = true
+  site_xml['hbase.coprocessor.master.classes'] = org.apache.hadoop.hbase.security.access.AccessController
+  site_xml['hbase.coprocessor.region.classes'] = org.apache.hadoop.hbase.security.access.AccessController,org.apache.hadoop.hbase.security.token.TokenProvider,org.apache.hadoop.hbase.security.access.SecureBulkLoadEndpoint
```

Apply Hbase Acl permissions:
```
#To Show all permissions on @SYSTEM NAMESPACE
user_permission '@SYSTEM'

#Grant Read only permission on @SYSTEM Namespace.
grant 'user', 'R' , 'SYSTEM:CATALOG'

#Grant respective 'RWXCA' [READ('R'), WRITE('W'), EXEC('X'), CREATE('C'), ADMIN('A')] permissions on user namespace
grant 'user', 'RWXCA' , '@userNamespace'
```

**Comment by bijugs** [comment]
Thanks @saumilmayani . Refer issue #1110 for enabling Phoenix security feature. Also the original intention of the PR was to add these properties and not to enable namespace mapping.

**Comment by bijugs** [comment]
Tested the PR as it is on a VM cluster with ``HDP 2.6.1`` and it had no impact. Will wait to get ``2.6.3`` in to test on it.

**Comment by cbaenziger** [comment]
@bijugs To confirm you will be enabling both of these as well as defining them, correct?

**Comment by aespinosa** [comment]
@bijugs can you list the things we should be monitoring on hbase and phoenix when we roll it out?

**Comment by bijugs** [comment]
Once ``phoenix.schema.isNamespaceMappingEnabled`` is set to ``true`` on server and client, the first access of the client to the server will move the system tables to ``system`` namespace. That will be the main change. Will update with more details once tested on ``2.6.3`` .

**Comment by aespinosa** [comment]
`2.6.3` merged to master #1107

**Comment by bijugs** [comment]
Testing done with ``phoenix.schema.isNamespaceMappingEnabled`` set to ``true``

- Using ``hbase shell`` checked the namespaces
- Connected to ```Phoenix`` using ``sqlline.py`` from the worker node which is the first client connection which triggers the creation of ``SYSTEM`` namespace and moves the SYSTEM tables under it.
- Checked again the namespaces through ``hbase shell`` and verified that the ``SYSTEM`` namespace is created and the tables are moved
- Created a new schema in Phoenix and a table under the schema through ``sqlline.py`` which also created a new namespace in ``HBase``
- Did do a ``select`` from the new table after issuing ``use schemaname`` command in sqlline.py

**Comment by vt0r** [comment]
Sorry, @bijugs. I just created a merge conflict by merging #1119. I'll try to test this in a hardware cluster tomorrow morning regardless.

**Comment by vt0r** [comment]
Merge conflict resolved. Change was deployed to a dev hardware cluster for further testing. Will merge once testing is completed.

**Comment by vt0r** [comment]
Testing completed successfully on hardware.

**Pull request merged**
