### PR TITLE
Delete configuration no longer needed hive_server.rb and hive_metastore.rb

### PR DESCRIPTION
**Pull request by pu239ppy**
Recipe appears to not be used anymore

### CODE REVIEW

**Comment by cbaenziger** [comment]
Could you verify we can blow away `hive_metastore.rb` too please?

**Comment by pu239ppy** [comment]
Looks safe to delete as well

**Comment by cbaenziger** [comment]
Yea!

**Comment by cbaenziger** [comment]
Oops, could the commit/PR mention it is deleting more than `hive_server.rb`?

**Comment by pu239ppy** [comment]
Done

**Pull request merged**
