### PR TITLE
Disable ForkJoin validation in Oozie

### PR DESCRIPTION
**Pull request by aespinosa**
Set as a workaround until the next HDP 2.6 maintenance release.

### CODE REVIEW

**Comment by leochen4891** [comment]
I would suggest to use an attribute

**Comment by bijugs** [comment]
Better late than never. Can this be set at the workflow level based on the application need instead of disabling for the whole cluster?

**Comment by bijugs** [comment]
Thanks @dbist . That is my suggestion i.e. not to set ``oozie.wf.validate.ForkJoin`` to ``false`` in the server property by to let users to set it in the workflow level.

**Comment by dbist** [comment]
@bijugs the global property is `oozie.validate.ForkJoin=False`, per workflow property is `oozie.wf.validate.ForkJoin=false`, notice the subtle difference

**Comment by bijugs** [comment]
:-)... setting "oozie.wf.validate.ForkJoin=false" at the server level will disable the validation for all workflows. Correct @dbist ? If so do we want to do that? Would it not be better to leave it to the users to determine whether they want to disable the validation on the workflow level.

**Comment by dbist** [comment]
@bijugs `oozie.validate.ForkJoin=false` goes in oozie-site, `oozie.wf.validate.ForkJoin=false` goes in job.properties, its not meant to go server-side.

**Pull request merged**
