### PR TITLE
Adding new HDP GPL repo

### PR DESCRIPTION
**Pull request by vineshcpaul**
HDP 2.6.4 release onwards, there is an additional GPL repo. Adding the new repo.

### CODE REVIEW

**Comment by vineshcpaul** [comment]
Hi Clay,

I missed them, thanks for notifying.
Will update all the repos to 2.6.4 and point them to release repo.

Thanks
Vinesh

**Comment by aespinosa** [comment]
Can you describe what's in the GPL Repo and why it is needed now?

A few reference links and a summary should suffice.

**Comment by vijayk** [comment]
@aespinosa We have removed GPL licensed softwares from the HDP repo. It is left to end user to select the GPL repo in case they want to consume. 

Latest HDP is having only one package identified with GPL from HDP which is "hadooplzo" and is served through the hdp.gpl.repo|list.

Repo:
http://public-repo-1.hortonworks.com/HDP-GPL/ubuntu14/2.x/updates/2.6.4.0/hdp.gpl.list

/cc
@vineshcpaul

**Comment by aespinosa** [comment]
Thanks @vijayk !

Can you link the release note in 2.6.4/2.6.5 indicating that?

**Comment by cbaenziger** [comment]
Let's close this out for #1230 for 2.6.5 and we will simply skip 2.6.4 at this time.

**Pull request closed without merging**
