### PR TITLE
single mechanism for node decommissions

### PR DESCRIPTION
**Pull request by pu239ppy**
Use bcpc.hadoop.decommission.hosts for both yarn and hdfs decommission.

### CODE REVIEW

**Comment by cbaenziger** [comment]
Can we also use this to [drain](http://hbase.apache.org/1.2/book.html#draining.servers) HBase?

**Comment by vt0r** [comment]
:100: for this. Big improvement over my earlier version. Initial review looks good. Will look it over further on Monday.

**Comment by pu239ppy** [comment]
@cbaenziger I recall trying to drain HBase manually and it did not work.  Either way making zookeeper chnges, is a little harder then rendering a text file.  I will look into it but making no promises for this PR

**Comment by pu239ppy** [comment]
Once again I tried the /hbase/draining route and once again it did not work.  I love it how the hbase documentation briefly mentions it and then links to some blog post about it, where they talk about using fabric

**Pull request merged**
