### PR TITLE
hdp-select all packages by hand

### LINKED ISSUE #1061: upgrade all HDP symlinks
Today we do [`hdp_select('zookeeper-server')`](https://github.com/bloomberg/chef-bach/blob/6c250c0b5526dd00cdb953c7f7c81f957370cf45/cookbooks/bcpc-hadoop/recipes/zookeeper_packages.rb#L34-L35) but we do not update the `zookeeper-client` pointer today; we should though! Thanks to @leochen4891 for discovering this.

### PR DESCRIPTION
**Pull request by aespinosa**
Fixes #1061 

Head
- [x] namenodes
- [x] zookeeper via #1062 
- [x] journalnode
- [x] hbase-master
- [x] resourcemanager
- [x] oozie
- [x] hive

Worker
- [x] datanode / nodemanager
- [x] regionserver

### CODE REVIEW

**Comment by aespinosa** [comment]
Enumeration by hand:

```
apt-get install -y <thepackage>
# should contain all the hdp-selected symlinks
for i in /usr/hdp/current/*; do [ -d $(readlink $i) ] && basename $i ; done
```

**Comment by aespinosa** [comment]
There are also dead hdp-select symlinks being implicitly produced:

e.g. 

```
apt-get install -y hadoop-hdfs-namenode
# list dead symlinks
for i in /usr/hdp/current/*; do [ -d $(readlink $i) ] ||basename $i ; done
hadoop-httpfs
hadoop-mapreduce-client
hadoop-mapreduce-historyserver
hadoop-yarn-client
hadoop-yarn-nodemanager
hadoop-yarn-resourcemanager
hadoop-yarn-timelineserver
hive-client
livy2-client
livy-client
pig-client
tez-client
```

**Comment by aespinosa** [comment]
Missed packages on bcpc-vm2:
runlist:
```
 - role[BCPC-Hadoop-Head]
  - role[BCPC-Hadoop-Head-ResourceManager]
  - role[BCPC-Hadoop-Head-Namenode-Standby]
  - role[BCPC-Hadoop-Head-MapReduce]
  - role[BCPC-Hadoop-Head-Hive]
  - recipe[bcpc-hadoop::copylog]
  - role[BCPC-Hadoop-Head-YarnTimeLineServer]
```

Missed packages:
```
ls -l /usr/hdp/current | grep 2.6.1
lrwxrwxrwx 1 root root 25 Jan  5 13:51 hbase-client -> /usr/hdp/2.6.1.17-1/hbase
lrwxrwxrwx 1 root root 25 Jan  5 13:51 hbase-master -> /usr/hdp/2.6.1.17-1/hbase
lrwxrwxrwx 1 root root 25 Jan  5 13:51 hbase-regionserver -> /usr/hdp/2.6.1.17-1/hbase
```

**Comment by aespinosa** [comment]
Worker and namenode_master builds

**Comment by http-418** [comment]
Per our 1 Feb 18 code review, we probably no longer want the hdp-select changes on our side, with hardcoded strings.  We should push hwx to fix their hdp-select.

This PR should be cut down to just the linting fixes.

**Comment by aespinosa** [comment]
I'll preserve this PR and open a new one for lints so that we can refer to this case in the future.

**Pull request closed without merging**
