### PR TITLE
Change to make ZK connection more robust. issue 353

### PR DESCRIPTION
**Pull request by bijugs**
**Draft PR for comments**
-----------------------------
Making the ``ZooKeeper`` connect a bit more robust. Based on ``ZOOKEEPER-1057`` looks like if there is a failure with connecting to first node in the ZK host names passed i.e it is down, then connection seem to fail even though there is a ZK quorum.

### CODE REVIEW

**Comment by cbaenziger** [comment]
@bijugs thanks for these edits, however, as mentioned in #1074, I'd like to see a lot of this code removed in favor of bloomberg/locking_resource-cookbook (e.g.https://github.com/cbaenziger/chef-bach/commit/aa3c213f807ceeaa01cbd9cd903c4a6ed4c5cce3). What are your thoughts?

**Comment by bijugs** [comment]
Hi @cbaenziger , If we are close to incorporating the changes from ``locking-resource-cookbook`` soon then this is not required. If not, it may be good to consider any change to improve ZK connection so that we can help alleviate cluster issues.

**Comment by cbaenziger** [comment]
Hi @bijugs can this code be moved to locking_restart now that all locking code is there? For format zkfc, perhaps we can make a clean API from locking resource for it to use so we don't have duplicate code (or we just accept duplication for now).

**Comment by cbaenziger** [comment]
@bijugs Please commit this to  bloomberg/locking_resource-cookbook; closing here as no-longer applicable.

**Pull request closed without merging**
